# Generated by Django 5.2.14 on 2026-06-03 17:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, default=uuid.uuid4, max_length=64, unique=True)),
                ('word', models.CharField(max_length=10)),
                ('word_length', models.IntegerField()),
                ('guesses', models.JSONField(default=list)),
                ('results', models.JSONField(default=list)),
                ('hints_used', models.IntegerField(default=0)),
                ('is_complete', models.BooleanField(default=False)),
                ('is_won', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ойын сессиясы',
                'verbose_name_plural': 'Ойын сессиялары',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KazakhWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(db_index=True, max_length=10, unique=True)),
                ('length', models.IntegerField(db_index=True)),
                ('definition', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Қазақ сөзі',
                'verbose_name_plural': 'Қазақ сөздері',
                'ordering': ['word'],
            },
        ),
    ]
